name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️ Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️ Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

      # 5️ Deploy to Kubernetes if KUBE_CONFIG_DATA exists
      - name: Set up kubectl
        if: ${{ secrets.KUBE_CONFIG_DATA != '' }}
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        if: ${{ secrets.KUBE_CONFIG_DATA != '' }}
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Deploy updated image
        if: ${{ secrets.KUBE_CONFIG_DATA != '' }}
        run: |
          kubectl set image deployment/wisecow wisecow=${{ secrets.DOCKER_USERNAME }}/wisecow:latest --namespace default || echo "Deployment not found — skipping"
          kubectl apply -f k8s/ || echo "Kubernetes apply skipped"
