name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

      # ---- Kubernetes Deployment ----
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          if [ -n "$KUBE_CONFIG_DATA" ]; then
            mkdir -p $HOME/.kube
            echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
          else
            echo "⚠️ No KUBE_CONFIG_DATA secret found — skipping Kubernetes setup."
          fi

      - name: Deploy to Kubernetes
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          if [ -n "$KUBE_CONFIG_DATA" ]; then
            echo "Deploying updated image..."
            kubectl set image deployment/wisecow wisecow=${DOCKER_USERNAME}/wisecow:latest --namespace default || echo "Deployment not found — skipping"
            kubectl apply -f k8s/ || echo "No manifests found, skipping apply"
          else
            echo "⚠️ Skipping deploy since no kubeconfig is provided."
          fi
